apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-redis
spec:
  selector:
    matchLabels:
      app: chess-redis
  template:
    metadata:
      labels:
        app: chess-redis
    spec:
      volumes:
      - name: redis-data
        persistentVolumeClaim:
            claimName: redis-data
      containers:
      - name: chess-redis
        image: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: chess-redis
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  resources:
    requests:
      storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce