apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-worker
spec:
  selector:
    matchLabels:
      app: game-worker
  template:
    metadata:
      labels:
        app: game-worker
    spec:
      containers:
      - name: game-worker
        image: eu.gcr.io/silent-relic-333216/game-worker
        imagePullPolicy: Always
        env:
        - name: S3_HOST
          valueFrom:
              secretKeyRef:
                name: s3details
                key: S3_HOST
        - name: S3_ACCESS
          valueFrom:
            secretKeyRef:
              name: minio
              key: root-user
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              key: root-password
              name: minio
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
