apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-worker
spec:
  selector:
    matchLabels:
      app: bot-worker
  template:
    metadata:
      labels:
        app: bot-worker
    spec:
      containers:
      - name: bot-worker
        image: eu.gcr.io/silent-relic-333216/bot-worker
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
