apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-worker
spec:
  selector:
    matchLabels:
      app: game-worker
  template:
    metadata:
      labels:
        app: game-worker
    spec:
      containers:
      - name: game-worker
        image: eu.gcr.io/silent-relic-333216/game-worker
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
