apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-redis
spec:
  selector:
    matchLabels:
      app: chess-redis
  template:
    metadata:
      labels:
        app: chess-redis
    spec:
      containers:
      - name: chess-redis
        image: redis
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: chess-redis
  clusterIP: 10.0.128.46
  clusterIPs:
    - 10.0.128.46
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
