apiVersion: apps/v1
kind: Deployment
metadata:
  name: fen-worker
spec:
  selector:
    matchLabels:
      app: fen-worker
  template:
    metadata:
      labels:
        app: fen-worker
    spec:
      containers:
      - name: fen-worker
        image: eu.gcr.io/silent-relic-333216/fen-worker:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
