apiVersion: apps/v1
kind: Deployment
metadata:
  name: healer
spec:
  selector:
    matchLabels:
      app: healer
  template:
    metadata:
      labels:
        app: healer
    spec:
      containers:
      - name: healer
        image: eu.gcr.io/silent-relic-333216/healer:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
        ports:
        - containerPort: 5060
          name: healer-mon
