name: tag-em
on:
  push:
    branches:
      - main

jobs:
  tagem:
    name: tagem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag commit
        run: git tag -f cw_ccbd_2020 HEAD
      - name: Push tag update
        run: git push --tags
